import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams.update({
    "pgf.texsystem": "pdflatex",
    'font.family': 'serif',
    'text.usetex': True,
    'pgf.rcfonts': False,
})
plt.rcParams['axes.prop_cycle'] = plt.cycler(color=plt.cm.Set1(np.linspace(0, 1, 10)))

# Load all .csv files in ./store folder
def load_data():
    data = {}
    for file in os.listdir("../data"):
        if file.endswith(".csv"):
            name = file.split(".")[0]
            data[name] = pd.read_csv(f"../data/{file}")
    return data

# Load all .csv files in ./store folder
data = load_data()

# Compare i100 for linux and linux rt
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h_histogram']['time'], data['linux-i100-1h_histogram']['core1'], label='PREEMPT')
plt.semilogy(data['linux-rt-i100-1h_histogram']['time'], data['linux-rt-i100-1h_histogram']['core1'], label='PREEMPT_RT')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-vs-rt-linux-i100-1h.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux only for all cores
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h_histogram']['time'], data['linux-i100-1h_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-i100-1h_histogram']['time'], data['linux-i100-1h_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-i100-1h_histogram']['time'], data['linux-i100-1h_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-i100-1h_histogram']['time'], data['linux-i100-1h_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-i100-1h-allcores.pdf', format='pdf', bbox_inches='tight')

# Compare i100 for linux rt only for all cores
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-rt-i100-1h_histogram']['time'], data['linux-rt-i100-1h_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-rt-i100-1h_histogram']['time'], data['linux-rt-i100-1h_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-rt-i100-1h_histogram']['time'], data['linux-rt-i100-1h_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-rt-i100-1h_histogram']['time'], data['linux-rt-i100-1h_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-rt-i100-1h-allcores.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux and linux rt under CPU load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core1'], label='PREEMPT')
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core1'], label='PREEMPT_RT')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-vs-rt-linux-i100-1h-sc4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux only for all cores under CPU load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-i100-1h-allcores-sc4.pdf', format='pdf', bbox_inches='tight')

# Compare i100 for linux rt only for all cores under CPU load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-rt-i100-1h-allcores-sc4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux and linux rt under Memory load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h-sm4_histogram']['time'], data['linux-i100-1h-sm4_histogram']['core1'], label='PREEMPT')
plt.semilogy(data['linux-rt-i100-1h-sm4_histogram']['time'], data['linux-rt-i100-1h-sm4_histogram']['core1'], label='PREEMPT_RT')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-vs-rt-linux-i100-1h-sm4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux only for all cores under Memory load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h-sm4_histogram']['time'], data['linux-i100-1h-sm4_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-i100-1h-sm4_histogram']['time'], data['linux-i100-1h-sm4_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-i100-1h-sm4_histogram']['time'], data['linux-i100-1h-sm4_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-i100-1h-sm4_histogram']['time'], data['linux-i100-1h-sm4_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-i100-1h-allcores-sm4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for linux rt only for all cores under Memory load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-rt-i100-1h-sm4_histogram']['time'], data['linux-rt-i100-1h-sm4_histogram']['core1'], label='Core 1')
plt.semilogy(data['linux-rt-i100-1h-sm4_histogram']['time'], data['linux-rt-i100-1h-sm4_histogram']['core2'], label='Core 2')
plt.semilogy(data['linux-rt-i100-1h-sm4_histogram']['time'], data['linux-rt-i100-1h-sm4_histogram']['core3'], label='Core 3')
plt.semilogy(data['linux-rt-i100-1h-sm4_histogram']['time'], data['linux-rt-i100-1h-sm4_histogram']['core4'], label='Core 4')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-rt-i100-1h-allcores-sm4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 vs i200 vs i500 vs i1000 for linux rt under cpu load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-rt-i100-1h-sc4_histogram']['time'], data['linux-rt-i100-1h-sc4_histogram']['core1'], label='i100')
plt.semilogy(data['linux-rt-i200-1h-sc4_histogram']['time'], data['linux-rt-i200-1h-sc4_histogram']['core1'], label='i200')
plt.semilogy(data['linux-rt-i500-1h-sc4_histogram']['time'], data['linux-rt-i500-1h-sc4_histogram']['core1'], label='i500')
plt.semilogy(data['linux-rt-i1000-1h-sc4_histogram']['time'], data['linux-rt-i1000-1h-sc4_histogram']['core1'], label='i1000')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-rt-i100-i1000-1h-sc4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 vs i200 vs i500 vs i1000 for linux under cpu load
plt.figure(figsize=(8,2))
plt.semilogy(data['linux-i100-1h-sc4_histogram']['time'], data['linux-i100-1h-sc4_histogram']['core1'], label='i100')
plt.semilogy(data['linux-i200-1h-sc4_histogram']['time'], data['linux-i200-1h-sc4_histogram']['core1'], label='i200')
plt.semilogy(data['linux-i500-1h-sc4_histogram']['time'], data['linux-i500-1h-sc4_histogram']['core1'], label='i500')
plt.semilogy(data['linux-i1000-1h-sc4_histogram']['time'], data['linux-i1000-1h-sc4_histogram']['core1'], label='i1000')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../linux-i100-i1000-1h-sc4.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for xen rt with rt guest under cpu load
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-i100-sc1-1h_histogram']['time'], data['xen-rt-i100-sc1-1h_histogram']['core1'], label='Dom0')
plt.semilogy(data['xen-rt-vm-rt-guest-i100-sc1-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i100-sc1-1h_histogram']['core1'], label='Dom1')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-i100-1h-sc1.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for xen rt with rt guest under no load
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-i100-1h_histogram']['time'], data['xen-rt-i100-1h_histogram']['core1'], label='Dom0')
plt.semilogy(data['xen-rt-vm-rt-guest-i100-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i100-1h_histogram']['core1'], label='Dom1')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-i100-1h.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 vs i200 vs i500 vs i1000 for xen guest rt under cpu load
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-vm-rt-guest-i100-sc1-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i100-sc1-1h_histogram']['core1'], label='i100')
plt.semilogy(data['xen-rt-vm-rt-guest-i200-sc1-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i200-sc1-1h_histogram']['core1'], label='i200')
plt.semilogy(data['xen-rt-vm-rt-guest-i500-sc1-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i500-sc1-1h_histogram']['core1'], label='i500')
plt.semilogy(data['xen-rt-vm-rt-guest-i1000-sc1-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i1000-sc1-1h_histogram']['core1'], label='i1000')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-i100-i1000-1h-sc1.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 vs i200 vs i500 vs i1000 for xen guest rt under no load
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-vm-rt-guest-i100-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i100-1h_histogram']['core1'], label='i100')
plt.semilogy(data['xen-rt-vm-rt-guest-i200-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i200-1h_histogram']['core1'], label='i200')
plt.semilogy(data['xen-rt-vm-rt-guest-i500-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i500-1h_histogram']['core1'], label='i500')
plt.semilogy(data['xen-rt-vm-rt-guest-i1000-1h_histogram']['time'], data['xen-rt-vm-rt-guest-i1000-1h_histogram']['core1'], label='i1000')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-i100-i1000-1h.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 for xen rt with rt guest under no load (slop)
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-slop-i100-1h_histogram']['time'], data['xen-rt-slop-i100-1h_histogram']['core1'], label='Dom0')
plt.semilogy(data['xen-rt-slop-vm-rt-guest-i100-1h_histogram']['time'], data['xen-rt-slop-vm-rt-guest-i100-1h_histogram']['core1'], label='Dom1')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-slop-i100-1h.pdf', format='pdf', bbox_inches='tight')
plt.close()

# Compare i100 vs i200 vs i500 vs i1000 for xen guest rt under no load (slop)
plt.figure(figsize=(8,2))
plt.semilogy(data['xen-rt-slop-vm-rt-guest-i100-1h_histogram']['time'], data['xen-rt-slop-vm-rt-guest-i100-1h_histogram']['core1'], label='i100')
plt.semilogy(data['xen-rt-slop-vm-rt-guest-i200-1h_histogram']['time'], data['xen-rt-slop-vm-rt-guest-i200-1h_histogram']['core1'], label='i200')
plt.semilogy(data['xen-rt-slop-vm-rt-guest-i500-1h_histogram']['time'], data['xen-rt-slop-vm-rt-guest-i500-1h_histogram']['core1'], label='i500')
plt.semilogy(data['xen-rt-slop-vm-rt-guest-i1000-1h_histogram']['time'], data['xen-rt-slop-vm-rt-guest-i1000-1h_histogram']['core1'], label='i1000')
plt.legend()
plt.grid()
plt.margins(0)
plt.xlim(0, 500)
plt.ylim( (pow(10,0),pow(10,8)) )
plt.xlabel('Latency (us)')
plt.ylabel('Frequency')
plt.savefig('../xen-rt-slop-i100-i1000-1h.pdf', format='pdf', bbox_inches='tight')
plt.close()